In [ ]:
from structural_loads.domain import actions, loadcase

In [ ]:
einwirkung = actions.ActionDefinition(actions.ActionCategory.ANPRALL)

In [ ]:
einwirkung

ActionDefinition(category=<ActionCategory.ANPRALL: 'Anpralllast'>, type=<ActionType.ACCIDENTAL: 'Aussergewöhnlich'>, factors=ActionFactors(psi_0=1.0, psi_1=1.0, psi_2=1.0, duration_class=<DurationClass.VERY_SHORT: 'very_short'>), description='')

In [ ]:
einwirkung.to_dict()

{'category': 'Anpralllast',
 'type': 'Aussergewöhnlich',
 'description': '',
 'factors': {'psi_0': 1.0,
  'psi_1': 1.0,
  'psi_2': 1.0,
  'duration_class': 'very_short'}}

In [ ]:
einwirkung.to_df()

,category,type,description,psi_0,psi_1,psi_2,duration_class
0,Anpralllast,Aussergewöhnlich,,1.0,1.0,1.0,very_short

In [ ]:
lc1 = loadcase.LoadCase("LC1", actions.ActionCategory.ROOF)

In [ ]:
lc1.to_dict()

{'name': 'LC1', 'category': 'Kat. H: Dächer', 'description': None}

In [ ]:
lc1.to_df()

  name        category description
0  LC1  Kat. H: Dächer        None